version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mock-upstream:
    build:
      context: ../examples/mock_upstream
      dockerfile: Dockerfile
    ports: ["9000:9000"]

  gateway:
    build:
      context: ..
      dockerfile: infra/Dockerfile.gateway
    environment:
      - UPSTREAM_BASE_URL=${UPSTREAM_BASE_URL:-http://mock-upstream:9000}
      - REDIS_URL=redis://redis:6379/0
      - ADMIN_API_KEY=${ADMIN_API_KEY:-my-admin-key}
      - DEFAULT_DAILY_LIMIT=${DEFAULT_DAILY_LIMIT:-100000}
      - DEFAULT_MONTHLY_LIMIT=${DEFAULT_MONTHLY_LIMIT:-1000000}
      - DEFAULT_RATE_PER_SEC=${DEFAULT_RATE_PER_SEC:-2.0}
      - DEFAULT_BURST=${DEFAULT_BURST:-5}
      - PORT=8080
    ports: ["8080:8080"]
    depends_on: [redis, mock-upstream]
    volumes:
      - ../atlas_gateway:/app/atlas_gateway      # bind mount source
      - ../examples:/app/examples                # optional: bind mount examples
      - ../tests:/app/tests                      # optional: bind mount tests
    command: uvicorn atlas_gateway.main:app --host 0.0.0.0 --port 8080 --reload
